### PR TITLE
Parses expected test failures

### PR DESCRIPTION
**Pull request by fonkadelic**
When using `XCTest`s [expected failures](https://developer.apple.com/documentation/xctest/expected_failures) the status value of the test result is "Expected Failure". Those tests should be marked as _Passed_ in the generated report instead of _Failed_.

### CODE REVIEW

**Comment by fonkadelic** [comment]
@renep I'm not sure about the target branch (`main` or `develop`). Feel free to change.

**Comment by BastianKusserow** [comment]
Hey @renep, is there already a release with those changes? :) And if not, would you be so kind and create one?

**Comment by renep** [comment]
I have create now a 0.23 release with this pull request.

**Comment by BastianKusserow** [comment]
@renep I just checked out 0.23.0.26 and it seems like it doesn't contain these changes. Is the 0.23.0.26 build from main? Since there the commit isn't included and there is no 0.23.0.develop on openbakery.

**Comment by renep** [comment]
You are right. (Silly Me 🙈)
There should be a 0.23.1 version now.

**Pull request merged**
