### PR TITLE
Codesign customization

### PR DESCRIPTION
**Pull request by BamX**
This will allow you to use custom codesigning tool or anything that allow you to sign bundles.
Related to #212

### CODE REVIEW

**Comment by renep** [comment]
I'm wondering...
You just add a closure so that your code is called that is in the build.gradle that does the codesign. Why do you need this closure?
If the package does a codesign, and afterwards you call your custom codesign, than the result is the same.

The goal of the plugin is to remove complexity. I wondering if it is a good idea to introduce such complexity.

I'm also wondering what the use case is that you need this? I first thought that you need additional parameters for codesign, because of some things I have missed?

**Comment by BamX** [comment]
In our company we have remote signing service that controls all certificates. This small property is a simpliest way to enable signing service in your plugin. For everybody else there will be no significant changes, no additional complexity will be added. I could provide additional description to this property in documentation or remove it from documentation at all.

**Comment by BamX** [comment]
So, could it be merged?

**Comment by renep** [comment]
The goal of the plugin is to reduce complexity and hide the logic how to codesign or how that stuff is packed into an ipa.

Therefor I do not have a good feeling to introduce a parameter that is a closure.

If I understand this correctly you need a package that is not signed, because you have an internal service where the application is signed. Therefor you also do not need the keychain setup and provisioning install prior to the package task.

What if there is an option that the package task does no signing at all?

You that run the package tasks, and afterward you can do your custom signing.

**Comment by BamX** [comment]
It's good idea to add this option. After all I'll have to unzip ipa, sign app and zip it again?

**Comment by renep** [comment]
The unzip Payload is still in the build/package path. So you have just to sign this an zip it again.

**Comment by BamX** [comment]
Thats clear. Could you add an option to disable signing on package step? Or should I work with it?
This pull-request could be declined.

**Comment by renep** [comment]
I thinking that we do not need any new option. If no signing settings were specified like certificateURI and mobileProvisionURI then no signing should be performed. No extra option is needed here to achieve this.

If you like you can implement this, but make sure that you do not brake the unit tests, an new tests for this would be highly appreciated.

**Comment by BamX** [comment]
Ok. I'll try not specifying signing settings first. Thank you!

**Pull request closed without merging**
