### PR TITLE
Fix for wrong entitlements application-identifier in case of InHouse wildcard provisioning profile

### PR DESCRIPTION
**Pull request by endrelzr**
This is a possible fix for #229. We were pushed to deploy our app so this was the quickest way I found. I ran the tests and all passed, however I hadn't have time to check what test case would cover this scenario.

### CODE REVIEW

**Comment by renep** [comment]
What does your code fix?

If the variable `currentValue` contains the string `AAAAAAAAAA.*` then:
`currentValue[0..-2]` gives `AAAAAAAAAA.`
and 
`currentValue.substring(0, currentValue.indexOf('.') + 1)` gives also `AAAAAAAAAA.`

So I don't get it what this pull request fixes.

**Comment by endrelzr** [comment]
Yes but if the currentValue contains AAAAAAAAAA.com.mycompany.* then 
```currentValue[0..-2]``` gives ```AAAAAAAAAA.com.mycompany```
and 
```currentValue.substring(0, currentValue.indexOf('.') + 1)``` gives only ```AAAAAAAAAA``. 

The provisioning profile which generated the entitlements mentioned in #229 contains the following:
```
	<key>Entitlements</key>
	<dict>
		<key>keychain-access-groups</key>
		<array>
			<string>AAAAAAAAAA.*</string>
		</array>
		<key>get-task-allow</key>
		<false/>
		<key>application-identifier</key>
		<string>AAAAAAAAAA.com.mycompany.*</string>
		<key>com.apple.developer.team-identifier</key>
		<string>AAAAAAAAAA</string>

	</dict>
```

**Comment by endrelzr** [comment]
@renep 
What's the status of this pull request? 
I've just tested the 0.12.5 version and the issue is still the same in case of InHouse wildcard provisioning profile.

**Comment by renep** [comment]
It is on my todos list for the next version. The 0.12.5 was a Quickfix that was a matter of minutes. I want to do this issue right and just extracting the first part, is in my opinion not the proper way.
When you have AAAAAAAAA.com.mycompany.* in the provisioining profile, but you bundle identifier is com.example then this does not work and the build should fail.

**Comment by renep** [comment]
Implemented in the development branch.

**Comment by endrelzr** [comment]
@renep 
I tested today the latest version from the develop branch and it works as expected. 
Thank you for fixing this.

**Comment by renep** [comment]
Thanks for the feedback. I'll try to create a new releases in the next few days.

**Comment by renep** [comment]
fixed with 0.12.7

**Pull request closed without merging**
