### PR TITLE
Cocoapods is more like gradle dependencies now

### PR DESCRIPTION
**Pull request by rahulsom**
Cocoapods sets up xcode to compare Manifest.lock and Podfile.lock to decide if pods are out of date.
I think it's nice if this plugin does the same.

### CODE REVIEW

**Comment by renep** [comment]
It is intentional that is is checked if the Pods directory exists and that the pod install is skipped if so.

The check with the Podfile.lock is done by cocoapods itself, so why duplicate the logic?

**Comment by rahulsom** [comment]
Right now, if you're working with a team and someone else updates Podfile, the gradle build fails.
With this commit, the gradle build will detect the difference between Podfile.lock and Manifest.lock and update the dependencies to match Podfile.lock.

The net effect is the user does not have to manually run `pod install`.

**Comment by renep** [comment]
Ok, now I get it. This is a good one ;)
I didn't know that the Manifest.lock contains the current installed version.

**Comment by renep** [comment]
merged into develop branch

**Comment by renep** [comment]
There are a bunch of unit tests in the project, so it would be nice if all unit tests would work for an pull request. (My continuous integration system found 3 failed tests)

**Comment by rahulsom** [comment]
Thanks. I'll get those fixed.

**Pull request closed without merging**
