### PR TITLE
Use correct xcresulttool version

### PR DESCRIPTION
**Pull request by BastianKusserow**
Currently the plugin uses the xcresulttool from the selected xcode command line tools. This leads to problems if a different xcode version was specified in the build.gradle file.

### CODE REVIEW

**Comment by BastianKusserow** [comment]
> Looks like the gradle version must be updated, because it does not work with OpenJDK 13.

So which version do you propose? 5.6.3?

**Comment by renep** [comment]
yes 5.6.3 should be fine

**Comment by BastianKusserow** [comment]
> yes 5.6.3 should be fine

Seems like 5.6.3 or 5.6.4 also do not support java 13. According to gradle.org, support for java 13 is planned for gradle 6.0. Do you know if the java version on travis can be specified somewhere?

**Comment by renep** [comment]
I updated now to gradle 6.0.1. I have to change some minor things in the project and was then able to merge this branch.

**Pull request merged**
