### PR TITLE
Support app extensions, including WatchKit

### PR DESCRIPTION
**Pull request by icecrystal23**
Allow entitlements changes to the app and extensions, and infoplist adjustments inside of the extensions.

### CODE REVIEW

**Comment by icecrystal23** [comment]
I couldn't fully test the example without provisioning profiles for the extensions.  If you can make provisioning profiles for this stuff, then I can test if the package step is actually working correctly.  It works in our project, but we have a rather complicated set up... so I wanted to make sure the simple case worked as well.

**Comment by renep** [comment]
Thanks for the pull request. WatchKit support will be an important feature ;-)

I had only a quick look and I'm wondering if the specifying of the extension is needed. Can the information not parsed from the project file?

I want to review this in detail soon, because I also have to check I all works fine with Xcode 7 ;-)

I also want to configure my CI machine to automatically build pull requests. For this is would be good if pull requests contains unit tests. I now always write tests for new features or changes, which has improved the quality of the plugin (imho)

**Comment by icecrystal23** [comment]
Hmm, we might be able to parse it out of the project file.  You can have targets that aren't being linked with the app, though, so we'd want to make sure those targets didn't get into the final package.

**Comment by savage7** [comment]
Any plans for WatchKit support? We currently release our builds with xcode archive because xcode gradle is not working with watchkit :(

**Comment by icecrystal23** [comment]
You're welcome to try my fork, which supports WatchKit. 

You'll have to build and distribute the plugin yourself, though. 

I haven't had time to write unit tests which AFAIK is why he hasn't accepted my pull request yet. 

Also, Xcode 7 may have an undocumented build parameter that may make supporting WatchKit easier (given to us at WWDC by an Apple dev).  We are going to try to switch to that soon for packaging the app.

**Comment by vstanishevsky** [comment]
Could you add supporting of Notification (Content/Service) extensions, please?

**Pull request merged**
