### PR TITLE
Cocoapods working dir

### LINKED ISSUE #356: cocopods fails due to working directory
With 0.14.4/0.14.5, If I have a subproject that uses cocoapods, xcodePlugin falls down:
```:myproj:cocoapodsInstall
Run pod setup
Setting up CocoaPods master repo
  $ /usr/local/bin/git -C /Users/asimmons/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 36, done.        
  remote: Compressing objects:   4% (1/21)           
  remote: Compressing objects:   9% (2/21)           
  remote: Compressing objects:  14% (3/21)           
  remote: Compressing objects:  19% (4/21)           
  remote: Compressing objects:  23% (5/21)           
  remote: Compressing objects:  28% (6/21)           
  remote: Compressing objects:  33% (7/21)           
  remote: Compressing objects:  38% (8/21)           
  remote: Compressing objects:  42% (9/21)           
  remote: Compressing objects:  47% (10/21)           
  remote: Compressing objects:  52% (11/21)           
  remote: Compressing objects:  57% (12/21)           
  remote: Compressing objects:  61% (13/21)           
  remote: Compressing objects:  66% (14/21)           
  remote: Compressing objects:  71% (15/21)           
  remote: Compressing objects:  76% (16/21)           
  remote: Compressing objects:  80% (17/21)           
  remote: Compressing objects:  85% (18/21)           
  remote: Compressing objects:  90% (19/21)           
  remote: Compressing objects:  95% (20/21)           
  remote: Compressing objects: 100% (21/21)           
  remote: Compressing objects: 100% (21/21), done.        
  remote: Total 36 (delta 22), reused 25 (delta 15), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     ddc65a2..9803371  master     -> origin/master
  $ /usr/local/bin/git -C /Users/asimmons/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/asimmons/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 9803371 [Add] Elemental 0.1.0
Setup completed
Run pod install
[!] No `Podfile' found in the project directory.
:myproj:cocoapodsInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myproj:cocoapodsInstall'.
> Command failed to run (exit code 1): '/usr/local/bin/pod install'
  Tail of output:
    remote: Compressing objects:  57% (12/21)           
    remote: Compressing objects:  61% (13/21)           
    remote: Compressing objects:  66% (14/21)           
    remote: Compressing objects:  71% (15/21)           
    remote: Compressing objects:  76% (16/21)           
    remote: Compressing objects:  80% (17/21)           
    remote: Compressing objects:  85% (18/21)           
    remote: Compressing objects:  90% (19/21)           
    remote: Compressing objects:  95% (20/21)           
    remote: Compressing objects: 100% (21/21)           
    remote: Compressing objects: 100% (21/21), done.        
    remote: Total 36 (delta 22), reused 25 (delta 15), pack-reused 0        
    From https://github.com/CocoaPods/Specs
       ddc65a2..9803371  master     -> origin/master
    $ /usr/local/bin/git -C /Users/asimmons/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
    master
    $ /usr/local/bin/git -C /Users/asimmons/.cocoapods/repos/master reset --hard origin/master
    HEAD is now at 9803371 [Add] Elemental 0.1.0
  Setup completed
  [!] No `Podfile' found in the project directory.
```

Investigation shows that `/usr/local/bin/pod install` is being run with a working directory of ".", which is where `gradlew` was invoked from.

### PR DESCRIPTION
**Pull request by paleozogt**
This fixes #356 and also adds more logging to `CommandRunner` so that we can see what its working directory is in the logs.

### CODE REVIEW

**Comment by phatblat** [comment]
👍  I fixed this in #344 but the change got reverted. Make sure to update the tests.

**Comment by paleozogt** [comment]
I'll fix up the cocopods test failures.  I didn't see them failing for all the other test failures, such as :
```org.openbakery.oclint.OCLintTaskTest > oclint_priority FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:326

org.openbakery.oclint.OCLintTaskTest > oclint_disableRule FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:367

org.openbakery.oclint.OCLintTaskTest > oclint FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:191

org.openbakery.oclint.OCLintTaskTest > oclintWithExclude FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:292

org.openbakery.oclint.OCLintTaskTest > untar FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:130

org.openbakery.oclint.OCLintTaskTest > oclintXcodebuild FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:158

org.openbakery.oclint.OCLintTaskTest > download FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:91

org.openbakery.oclint.OCLintTaskTest > oclintReportType FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:210

org.openbakery.oclint.OCLintTaskTest > oclintWithRules FAILED
    java.lang.AssertionError at OCLintTaskTest.groovy:251````

**Comment by paleozogt** [comment]
@phatblat I've updated the cocoapods unit-tests and now they're passing on travis.

I'm still seeing the `OCLintTaskTest` failures locally, but I guess that's a different problem (#358).

**Comment by renep** [comment]
Can you make the pull request not from `master`, but from the `develop` branch?

**Comment by paleozogt** [comment]
@renep I changed the PR to be on `develop`

**Pull request merged**
