### PR TITLE
Append projectFile to projectDir

### PR DESCRIPTION
**Pull request by phatblat**
Fixes build invocation from parent project for multiproject builds.

### CODE REVIEW

**Comment by renep** [comment]
My internal build server shows that 5 unit tests are failing.

**Comment by phatblat** [comment]
Yeah, I got those 5 test failures locally before I made any changes. Does master test clean for you?

**Comment by renep** [comment]
There was an issue on the master branch, that one dummy provisioning profile contained a date that was expired and therefor the test did not work. This was already fixed in the develop branch and with the latest release this is also in master.

For pull requests also see: https://github.com/openbakery/gradle-xcodePlugin#collaborate

**Comment by phatblat** [comment]
Ah, I branched from master. I'll rebase, retest and may move this to a new PR.

**Pull request merged**
