### PR TITLE
PackageTask xcodebuild parameters set

### PR DESCRIPTION
**Pull request by jussisalmi**
PackageTask xcodebuild parameters set

### CODE REVIEW

**Comment by renep** [comment]
Can you please describe what you problem so that I understand what this change should solve?

**Comment by jussisalmi** [comment]
Of course. At least when a project has Swift enabled Xcodebuild.loadBuildSettings() gets called in the Package task. The call works fine as long as xcodebuild command finds project, workspace or package from the current working directory. 

Currently, both parameters.scheme and parameters.workspace are null when the loadBuildSettings method gets executed. It happens, because Package task gives a newly created instance of the XcodebuildParameters to Xcodebuild constructor. Therefore, when project, workspace or package isn't located in the current working directory xcodebuild gives the error below.

xcodebuild: error: The directory <folder> does not contain an Xcode project, workspace or package.

Package task should give the parameters defined for the project to have the correct scheme and workspace for the loadBuildSettings method.

**Comment by jussisalmi** [comment]
Hi! Would you be able to consider merging this PR. It's quite obvious bug since the build params don't get propagated down the call path.

**Comment by renep** [comment]
Sorry but I have reverted your pull request in the latest release. The problem was that the Unit Test caused a NullPointerException and did not pass. Maybe this is related to my setup, but I have not investigated in detail.
I use Java11 now for building the plugin, because I have not yet found time to migrate to newer Java and to a newer gradle. I hope I find time to address this soon.

**Pull request merged**
