### PR TITLE
Updated WatchKit Support

### PR DESCRIPTION
**Pull request by fonkadelic**
This PR updates the support for archiving and packaging apps with WatchKit.
Including the following:
* Copy the WatchSupport Folder
* Add WatchKit Swift Frameworks
* Copy Watch Extension Frameworks
* Strips bitcode from Swift frameworks if needed
* Including the support folder only for AppStore IPAs

### CODE REVIEW

**Comment by renep** [comment]
it this ready to merge?

**Comment by renep** [comment]
can you test develop build `0.15.3.develop.131`

**Comment by Miiha** [comment]
Hi @renep, we tested uploading to TestFlight. Everything worked well

**Comment by renep** [comment]
Nice. So I will try to release a new 0.15.2 version soon.

**Pull request merged**
