### PR TITLE
Resolved Exception (allways reproducible) on xcodebuild.environment =…

### PR DESCRIPTION
**Pull request by semdangelo**
We  have discovered an issue of the plugin. 
That cause a crash every time you attempt to access from a build script to the environment variable. 
I've resolved the problem and as you can see, i have wrote two tests to proove the bug existance and its resolution with my commit.

### CODE REVIEW

**Comment by renep** [comment]
I would be nice if you could send me the pull request on the 'develop' branch, because I want to add new stuff only to the develop branch.
(If not I have to merge this manually, and this will be the next time a have time to work on the plugin)

**Comment by semdangelo** [comment]
Wow you are really reactive. I will try what you ask.

Actually i was fighting with the issue to serve the plugin with this fix in our internal maven repository... i think there is more than one think i'm missing ;(

**Comment by renep** [comment]
Not long a go I have setup a continuous deployment so that the version from the development branch gets automatically released when all the tests are green.
See: https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

**Comment by semdangelo** [comment]
Oh that's pretty good. 
Too bad i've already found and applied a workaround for that, i've wrote a bash script to clone my fork, build it locally and deploy on local repo. My collegues are using this script since yesterday. That was a critical issue for us, since we moved to gradle totally for our builds and one day of non-compilable code means many heads will fall. 
Thank you again, i'll see you on the next bug :P

**Pull request closed without merging**
