### PR TITLE
Disable signing if some properties have not been specified

### PR DESCRIPTION
**Pull request by BamX**
This changes allow package task to disable codesign if some required properties have not been specified. Package task will not fail but warning will be shown.

@renep I didn't add tests(and remove one), I don't know how to do it right for these changes. Does it need any documentation updates?

### CODE REVIEW

**Comment by BamX** [comment]
Related to #212 
@renep what do you say about it?

**Comment by renep** [comment]
Looks good, but I have not find the time to merge it, because I just want to finished the things im currently working on (= watchOS support)

**Comment by BamX** [comment]
Ok, I see. I'll be waiting

**Comment by renep** [comment]
watchOS support is working and I think tomorrow I will merge it and then I want to create a test release with all the new stuff ;-)

**Comment by renep** [comment]
15 failed unit tests!!!!

**Comment by BamX** [comment]
What's wrong?

**Comment by renep** [comment]
After merging I have to update 15 unit tests that where broken with the change. I have done that now, but in the future it is very very likely that I will not merge pull request that have failed unit test. ;-)

**Comment by BamX** [comment]
Ok. Sorry. I've tested my changes before fixing merge conflicts. Everything was just fine.

**Pull request merged**
